databases:
  - name: ewaste-db
    databaseName: ewaste_db
    user: ewaste_user
    plan: free

services:
  - type: web
    name: ewaste-backend
    env: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ewaste-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ewaste-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ewaste-db
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ewaste-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ewaste-db
          property: password
